services:
  bot:
    image: "skyndalex:bot"
    env_file:
      - .env
    links:
      - lavalink
    depends_on:
      - lavalink
  lavalink:
    image: ghcr.io/lavalink-devs/lavalink:4
    container_name: lavalink
    restart: unless-stopped
    environment:
      - _JAVA_OPTIONS=-Xmx6G
      - SERVER_PORT=6969
      - LAVALINK_SERVER_PASSWORD=${LAVALINK_AUTH}
    volumes:
      - ./application.yml:/opt/Lavalink/application.yml
      - ./plugins/:/opt/Lavalink/plugins/
    expose:
      - 6969
  db: 
    container_name: postgres
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
      POSTGRES_DB: skyndalexbeta
    volumes:
     - type: tmpfs
       target: /dev/shm
       tmpfs:
         size: 134217728  
    ports:
      - "5332:5432"