services:
  bot:
    image: "skyndalex:bot"
    env_file:
      - .env
    links:
      - lavalink
      - db
    depends_on:
      lavalink:
        condition: service_healthy
      db:
        condition: service_healthy
  lavalink:
    image: ghcr.io/lavalink-devs/lavalink:4
    container_name: lavalink
    restart: unless-stopped
    environment:
      - _JAVA_OPTIONS=-Xmx6G
      - SERVER_PORT=${LAVALINK_PORT}
      - LAVALINK_SERVER_PASSWORD=${LAVALINK_SERVER_PASSWORD}
    volumes:
      - ./application.yml:/opt/Lavalink/application.yml
      - ./plugins/:/opt/Lavalink/plugins/
    expose:
      - 6969
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6969"]
      interval: 30s
      timeout: 10s
      retries: 5
  db:
    container_name: postgres
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
      POSTGRES_DB: ${POSTGRES_DATABASE}
    volumes:
      - ./db:/data/postgres
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 134217728
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 5