import {
	type ChatInputCommandInteraction,
	SlashCommandBuilder,
	MediaGalleryBuilder,
	MessageFlags,
	ButtonBuilder,
	ButtonStyle,
	TextDisplayBuilder,
	ContainerBuilder,
	SeparatorBuilder,
	SeparatorSpacingSize,
	ActionRowBuilder,
	SectionBuilder, AttachmentBuilder,
} from "discord.js";
import type { SkyndalexClient } from "#classes";
import { Client } from "@gradio/client";
import { handleError } from "../../utils/index.js";
import * as process from "node:process";

export async function run(
	client: SkyndalexClient,
	interaction: ChatInputCommandInteraction,
) {
	try {
		await interaction.deferReply();

		const prompt = interaction.options.getString("prompt");
		const negative_prompt = interaction.options.getString("negative_prompt");
		const style = interaction.options.getString("style") || "2560 x 1440";

		const getToken = await client.prisma.tokens.findUnique({
			where: {
				userId: interaction.user.id,
			},
		});

		const defaultSpace = "Dagfinn1962/Midjourney-Free";
		const app = await Client.connect(defaultSpace, {
			hf_token: getToken?.huggingFaceToken,
		});

		const hasNegativePrompt = negative_prompt !== null;

		const result = await app.predict("/run", {
			prompt,
			negative_prompt,
			use_negative_prompt: hasNegativePrompt,
			style,
			seed: 0,
			width: 1024,
			height: 1024,
			guidance_scale: 0.1,
			randomize_seed: true,
		});

		if (result.error && !getToken?.huggingFaceToken) {
			const authorizeButton = new ButtonBuilder()
				.setLabel("Authorize")
				.setStyle(ButtonStyle.Link)
				.setURL(
					process.env.OAUTH_TO_HUGGINGFACE ?? "https://default-auth-url.com",
				);
			const row = new ActionRowBuilder<ButtonBuilder>().addComponents(
				authorizeButton,
			);

			const container = new ContainerBuilder().addTextDisplayComponents(
				new TextDisplayBuilder().setContent(
					"You need to authorize to use this command.",
				),
			);

			return interaction.editReply({
				flags: MessageFlags.IsComponentsV2,
				components: [container, row],
			});
		}

		console.log("getToken", getToken);
		console.log("negative_prompt", negative_prompt);
		console.log("style", style);
		console.log("result", result.data[0][0].image);

		if (result && result.data && result.data[0][0].image) {
			const deleteButton = new ButtonBuilder()
				.setCustomId("delete")
				.setLabel("Delete")
				.setStyle(ButtonStyle.Danger);

			const downloadButton = new ButtonBuilder()
				.setLabel("Download")
				.setStyle(ButtonStyle.Link)
				.setURL(result.data[0][0].image.url);

			const row = new ActionRowBuilder<ButtonBuilder>().addComponents(
				deleteButton,
				downloadButton,
			);

			const imageResponse = await fetch(result.data[0][0].image.url);
			const imageBuffer = Buffer.from(await imageResponse.arrayBuffer());
			const attachment = new AttachmentBuilder(imageBuffer, { name: 'generated-image.png' });

			await interaction.editReply({
				content: `**${prompt}** - Generated by **${interaction.user.username}** *(style: **${style}**)*`,
				components: [row],
				files: [attachment],
			});

		} else {
			await handleError(
				client,
				new Error("No image data returned from the model."),
				interaction,
			);
		}
	} catch (error) {
		console.error("Image generation error:", error);

		if (interaction.deferred || interaction.replied) {
			await handleError(
				client,
				new Error("An error occurred while generating the image."),
				interaction,
			);
		} else {
			await handleError(
				client,
				new Error("An error occurred while generating the image."),
				interaction,
			);
		}
	}
}

export const data = new SlashCommandBuilder()
	.setName("genimg")
	.setDescription("Generate an image using AI!")
	.addStringOption((option) =>
		option
			.setName("prompt")
			.setDescription("Describe the image you want to generate")
			.setRequired(true),
	)
	.addStringOption((option) =>
		option.setName("negative_prompt").setDescription("Negative prompt"),
	)
	.addStringOption((option) =>
		option
			.setName("style")
			.setDescription("Set style for a image")
			.addChoices(
				{ name: "2560 x 1440", value: "2560 x 1440" },
				{ name: "Photo", value: "Photo" },
				{ name: "Cinematic", value: "Cinematic" },
				{ name: "Anime", value: "Anime" },
				{ name: "3D Model", value: "3d_model" },
			),
	)
	.setIntegrationTypes([0, 1])
	.setContexts([0, 1, 2]);
